export const FindTypeActions = {
    SET_FILTERS: 'SET_FILTERS',
    SET_TEXT_FIND: 'SET_TEXT_FIND',
    SET_TEC_PAGE: 'SET_TEC_PAGE',
    SET_LAST_PAGE: 'SET_LAST_PAGE',
    SET_CARDS: 'SET_CARDS',
    SET_PER_PAGE: 'SET_PER_PAGE',
    SET_LOADING: 'SET_LOADING',
    SET_DATA_PAGE: 'SET_DATA_PAGE',
};